export const ROOMS_PER_TYPE = 5

export const ROOM_NAMES = [
  'Deluxe Garden View',
  'Deluxe Mountain View',
  'Honeymoon Suite',
  'The Evergreen Hill Suite',
  'Deluxe Twin Garden View',
  'Deluxe Twin Mountain View',
  'Family Suite',
  'Executive Suite',
] as const

export const ROOM_NAME_KEYS = [
  'deluxeGarden',
  'deluxeMountain',
  'honeymoonSuite',
  'evergreenSuite',
  'deluxeTwinGarden',
  'deluxeTwinMountain',
  'familySuite',
  'executiveSuite',
] as const

export const ROOM_IMAGES = {
  deluxeGarden: '/RoomsAndSuites/deluxe_garden_view.jpg',
  deluxeMountain: '/RoomsAndSuites/deluxe_mountain_view.jpg',
  honeymoonSuite: '/RoomsAndSuites/honeymoon_suite.jpg',
  evergreenSuite: '/RoomsAndSuites/the_evergreen_hill_suite.jpg',
  deluxeTwinGarden: '/RoomsAndSuites/deluxe_twin_garden_view.jpg',
  deluxeTwinMountain: '/RoomsAndSuites/deluxe_twin_mountain_view.jpg',
  familySuite: '/RoomsAndSuites/family_suite.jpg',
  executiveSuite: '/RoomsAndSuites/executive_suite.jpg',
} as const

export const ROOM_DATA = [
  {
    id: 1,
    nameKey: 'deluxeGarden',
    type: 'Room',
    price: 'From 350,000 MMK/night',
    guests: '2 Guests',
    size: '35 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'privateBathroom',
      'gardenView',
    ],
    imageAlt: 'Deluxe Garden View',
    imageUrl: '/RoomsAndSuites/deluxe_garden_view.jpg',
  },
  {
    id: 2,
    nameKey: 'deluxeMountain',
    type: 'Room',
    price: 'From 450,000 MMK/night',
    guests: '2 Guests',
    size: '40 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'privateBalcony',
      'mountainView',
    ],
    imageAlt: 'Deluxe Mountain View',
    imageUrl: '/RoomsAndSuites/deluxe_mountain_view.jpg',
  },
  {
    id: 3,
    nameKey: 'honeymoonSuite',
    type: 'Suite',
    price: 'From 950,000 MMK/night',
    guests: '2 Guests',
    size: '70 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'privateJacuzzi',
      'romanticSetting',
    ],
    imageAlt: 'Honeymoon Suite',
    imageUrl: '/RoomsAndSuites/honeymoon_suite.jpg',
  },
  {
    id: 4,
    nameKey: 'evergreenSuite',
    type: 'Suite',
    price: 'From 1,350,000 MMK/night',
    guests: '4 Guests',
    size: '95 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'butlerService',
      'luxuryAmenities',
    ],
    imageAlt: 'The Evergreen Hill Suite',
    imageUrl: '/RoomsAndSuites/the_evergreen_hill_suite.jpg',
  },
  {
    id: 5,
    nameKey: 'deluxeTwinGarden',
    type: 'Room',
    price: 'From 350,000 MMK/night',
    guests: '2 Guests',
    size: '35 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'privateBathroom',
      'gardenView',
    ],
    imageAlt: 'Deluxe Twin Garden View',
    imageUrl: '/RoomsAndSuites/deluxe_twin_garden_view.jpg',
  },
  {
    id: 6,
    nameKey: 'deluxeTwinMountain',
    type: 'Room',
    price: 'From 450,000 MMK/night',
    guests: '2 Guests',
    size: '40 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'privateBathroom',
      'mountainView',
    ],
    imageAlt: 'Deluxe Twin Mountain View',
    imageUrl: '/RoomsAndSuites/deluxe_twin_mountain_view.jpg',
  },
  {
    id: 7,
    nameKey: 'familySuite',
    type: 'Suite',
    price: 'From 650,000 MMK/night',
    guests: '4 Guests',
    size: '65 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'livingArea',
      'familyFriendly',
    ],
    imageAlt: 'Family Suite',
    imageUrl: '/RoomsAndSuites/family_suite.jpg',
  },
  {
    id: 8,
    nameKey: 'executiveSuite',
    type: 'Suite',
    price: 'From 800,000 MMK/night',
    guests: '2 Guests',
    size: '55 sqm',
    features: [
      'freeWifi',
      'smartTv',
      'coffeeTeaMaker',
      'airConditioning',
      'premiumAmenities',
      'panoramicView',
    ],
    imageAlt: 'Executive Suite',
    imageUrl: '/RoomsAndSuites/executive_suite.jpg',
  },
] as const

export type RoomNameKey = (typeof ROOM_NAME_KEYS)[number]
